import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const title: string = 'Next.js plus TypeScript';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className='title'>{title}</h1>
      </main>
    </div>
  );
}
